---
# Install Windows Updates on Application servers parallel
- name: Install Updates on Application Server and Terminal Server
  hosts: applicationserver, terminalserver
  strategy: free
  tasks:
    - name: search an install updates
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - DefinitionUpdates
          - UpdateRollups
          - Updates
        reboot: yes
        reboot_timeout: 3600
        log_path: c:\windows\logs\ansible_update.log
      register: update_result

# Install Windows Updates on Domain controllers linear
- name: Install Updates on Domain Controller
  hosts: domaincontroller
  tasks:
    - name: search and install updates
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - DefinitionUpdates
          - UpdateRollups
          - Updates
        reboot: yes
        reboot_timeout: 3600
        log_path: c:\windows\logs\ansible_update.log
      register: update_result

# Install Windows Updates on Hypervisor
- name: Install Updates on Hyper-V
  hosts: hypervisor
  tasks:
    - name: search and install updates
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - DefinitionUpdates
          - UpdateRollups
          - Updates
        reboot: no
        reboot_timeout: 3600
        log_path: c:\windows\logs\ansible_update.log
      register: update_result
